on: push

name: Test Create Issue

jobs:
  test-create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - run: yarn install
    - run: yarn test

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: ./
      with:
        project: CREATE
        issuetype: Epic
        summary: Do the thing for ${{ github.repository }}
        description: Compare branch|${{ github.event.compare }} # https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads
        fields: '{"customfield_10171": "field value from actions. Please do not remove"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
